---
#    - name: test the module    with friendly version
#      ldap: 
#        mode:
#          friendly:
#            firstname: 'char_temp3'               # aliases don't work the way i want them to :(
#            lastname: "Ash's"     
#            groups: 'Fire, Pokemon'
#       state: present 
#       admin_cn: "{{ admin_cn }}"
#       admin_pass: "{{ admin_pass }}" 
#       server: "{{ server }}"


    - name: test the module    with friendly version
      ldap: 
        mode:
          friendly:
            gn: 'char_temp3'
            sn: "Ashs"
            ou: 'Fire, Pokemon'
        state: present 
        admin_cn: "{{ admin_cn }}"
        admin_pass: "{{ admin_pass }}" 
        server_hostname: "{{ server_hostname }}"
        server_domain: "{{ server_domain }}"


#   - name: test the module      with dn
#      ldap: 
#        mode:
#          dn:
#            dn:  'cn=Bal_temp2,ou=Water,ou=Pokemon,dc=localdomain'
#        state: present 
#        admin_cn: "{{ admin_cn }}"
#        admin_pass: "{{ admin_pass }}" 
#        server: "{{ server }}"




