---
 - hosts: all
   tasks:
#    - name: test the module    with friendly version
#      ldap: 
#        mode:
#          friendly:
#            firstname: 'char_temp3'               # aliases don't work the way i want them to :(
#            lastname: "Ash's"     
#            groups: 'Fire, Pokemon'
#        state: present 


    - name: test the module    with friendly version
      ldap: 
        mode:
          friendly:
            gn: 'char_temp3'
            sn: "Ash's"
            ou: 'Fire, Pokemon'
        state: present 



#   - name: test the module      with dn
#      ldap: 
#        mode:
#          dn:
#            dn:  'cn=Bal_temp2,ou=Water,ou=Pokemon,dc=localdomain'
#        state: present 




